export const TOGGLE_PLUS_MINUS = "TOGGLE_PLUS_MINUS";
export const CALCULATE_RESULT = "CALCULATE_RESULT";
export const SAVE_EXPRESSION = "SAVE_EXPRESSION";
export const CLEAR_RESULT = "CLEAR_RESULT";
